###
//Create a new user (Admin)
POST http://localhost:5000/api/v1/user
Content-Type: application/json

{
  "user_fullname": "Chye Zee Ching",
  "user_email": "chingc217@gmail.com",
  "user_password": "ching",
  "user_confirmPassword": "ching",
  "user_role": "Admin",
  "user_phone": "0105650214"
}

###
//Create a new user (Farmer)
POST http://localhost:5000/api/v1/user
Content-Type: application/json

{
  "user_fullname": "Yek Lek Yew",
  "user_email": "lekyew@gmail.com",
  "user_password": "yew",
  "user_confirmPassword": "yew",
  "user_role": "Farmer",
  "user_phone": "0146618038"
}


###
//Create a new user (Farmer)
POST http://localhost:5000/api/v1/user
Content-Type: application/json

{
  "user_fullname": "Leo",
  "user_email": "leo@gmail.com",
  "user_password": "leo",
  "user_confirmPassword": "leo",
  "user_role": "Farmer",
  "user_phone": "0186618038"
}

###
//Get All User
GET http://localhost:5000/api/v1/user

###
//Get User By Id
GET http://localhost:5000/api/v1/user/be7145a9-931b-4518-9490-9574a72d03ee

###
//Get User By Id
GET http://localhost:5000/api/v1/user/cc38cb7a-1255-4f48-b0e0-498324ff777d

###
//Update user (Admin)
PATCH http://localhost:5000/api/v1/user/9db8f238-9c7a-4ff5-bebb-84fe5ebba2da
Content-Type: application/json

{
  "user_fullname": "Chye Zee Ching",
  "user_email": "chingc217@gmail.com",
  "user_password": "",
  "user_confirmPassword": "",
  "user_role": "Farmer",
  "user_phone": "0105650214"
}

###
//Update user (Admin)
PATCH http://localhost:5000/api/v1/user/cc38cb7a-1255-4f48-b0e0-498324ff777d
Content-Type: application/json

{
  "user_fullname": "Yek Lek Yew",
  "user_email": "lekyew@gmail.com",
  "user_password": "yew",
  "user_confirmPassword": "yew",
  "user_role": "Worker",
  "user_phone": "0146618038"
}

###
//delete user
DELETE http://localhost:5000/api/v1/user/bec0e7f5-4a81-4e97-aca0-e6f271efc7b5

###
//Login user (Admin)
POST http://localhost:5000/login
Content-Type: application/json

{
  "user_email": "chingc217@gmail.com",
  "user_password": "ching"
}

###
//Login user (Admin)
POST http://localhost:5000/login
Content-Type: application/json

{
  "user_email": "lekyew@gmail.com",
  "user_password": "yew"
}


###
GET http://localhost:5000/me


###
//Logout
DELETE http://localhost:5000/logout


###
//Get All CropList
GET http://localhost:5000/crop

###
//Create CropList
POST http://localhost:5000/crop
Content-Type: application/json

{
  "crop_name": "Lettuce"
}

###
//Get CropList by id
GET http://localhost:5000/crop/4af7cb88-c911-47d1-a800-7422e79cf5cc


###
//Update CropList
PATCH http://localhost:5000/crop/4af7cb88-c911-47d1-a800-7422e79cf5cc
Content-Type: application/json

{
  "crop_name": "Lettuce"
}


###
//Delete CropList
DELETE http://localhost:5000/crop/042145b4-a148-442e-a823-1fefb610ad32

